server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
#  cloud:
#    zookeeper:
#      connect-string: 192.168.56.111:2181

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.111:3306/db_cloud?useUnicode=true&characterEncoding=utf-8&useSSl=false
    username: wz
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.weizhen.springcloud.entities


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: false
    fetch-registry: true

logging:
  level:
    org.weizhen.springcloud.service.PaymentServiceFeign : debug