
---
server:
  port: 2003

spring:
  profiles:
    active: seata-account
  application:
    name: seata-account-server
  cloud:
    alibaba:
      seata:
        tx-service-group: account-server-group

    nacos:
      discovery:
        server-addr: 192.168.56.111:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.111:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSl=false
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: org.weizhen.springcloud.entities

management:
  endpoints:
    web:
      exposure:
        include: '*'

feign:
  hystrix:
    enabled: false


logging:
  level:
    io:
      seata: info