

---

server:
  port: 7001

eureka:
  instance:
    hostname: localhost
  #    hostname: localhost
  client:
    #是否向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心
    fetch-registry: false
    service-url:
      #设置与eureka注册地址格式
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://DESKTOP-ILMEDR9:7002/eureka/
spring:
  profiles: dev7001

---
server:
  port: 7002

eureka:
  instance:
    hostname: DESKTOP-ILMEDR9
#    hostname: localhost
  client:
    #是否向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心
    fetch-registry: false
    service-url:
      #设置与eureka注册地址格式
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:7001/eureka/

spring:
  profiles: dev7002
