---
server:
  port: 3344
spring:
  profiles: config3344
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jakjj/cloud-config.git
          search-paths:
            - cloud-config
      label: master

  rabbitmq:
    host: 192.168.56.111
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: config3344
    prefer-ip-address: true


#rabbitmq management
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: "bus-refresh"